yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:group_list>/', views.group_posts, name='group_list'),
    path('groups/', views.group_index, name='group_index'),
    path('groups/create/', views.group_create, name='group_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/comment/delete/',
        views.delete_comment,
        name='delete_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'

handler500 = 'core.views.server_error'

handler403 = 'core.views.permission_denied'

handler400 = 'core.views.bad_request'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/cycle_form.html
{% load user_filters %}
{% for field in form %}
  <div class="form-group row my-3"
    {% if login %}
      {% if field.field.required %} 
        aria-required="true"
      {% else %}
        aria-required="false"
      {% endif %}
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small 
           id="{{ field.id_for_label }}-help"
           class="form-text text-muted"
        >
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/errors_form.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<p>
  <a href="{% url 'about:author' %}" style="color:black">Об авторе</a> |
  <a href="{% url 'about:tech' %}" style="color:black">Технологии</a>
</p>
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar"> 
  <div class="container"> 
    <a class="blog-header-logo text-dark navbar-brand" href="{% url 'posts:index' %}"> 
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube 
    </a>
    <div class="drop">
      <button class="nav-btn">&#9776;</button>
      <div class="nav-list nav-tabs">
        {% with request.resolver_match.view_name as view_name %}
        {% if request.user.is_authenticated %}
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}" style="color:black">Новый пост</a>
          <a class="nav-link {% if view_name  == 'posts:profile' and author.username == user.username %}active{% endif %}" href="{% url 'posts:profile' user.username %}" style="color:black">&#128100; {{ user.username }}</a>
          <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" href="/auth/logout/" style="color:black">Выйти</a>
        {% else %}
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" href="/auth/login/" style="color:black">Войти</a>
          <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" href="/auth/signup/" style="color:black">Регистрация</a>
        {% endif %}
        {% endwith %}
      </div>
    </div>
  </div> 
</nav>    