yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:group_list>/', views.group_posts, name='group_list'),
    path('groups/', views.group_index, name='group_index'),
    path('groups/create/', views.group_create, name='group_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/comment/delete/',
        views.delete_comment,
        name='delete_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'

handler500 = 'core.views.server_error'

handler403 = 'core.views.permission_denied'

handler400 = 'core.views.bad_request'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models

from core.models import CreatedModel, User


class Post(CreatedModel):
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta(CreatedModel.Meta):
        verbose_name_plural = 'посты'
        default_related_name = 'posts'


class Group(models.Model):
    title = models.CharField(
        'название_группы',
        max_length=200,
        help_text='Введите название группы',
    )
    slug = models.SlugField(
        'ссылка',
        blank=True,
        null=False,
        unique=True,
        help_text='Введите ссылкy группы',
    )
    description = models.TextField(
        'описание группы',
        help_text='Введите описание группы'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='автор',
    )

    class Meta:
        verbose_name_plural = 'группы'

    def __str__(self):
        return self.title


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='пост'
    )

    class Meta(CreatedModel.Meta):
        verbose_name_plural = 'коментарии'
        default_related_name = 'comments'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='который подписывается',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='на которого подписываются',
    )

    class Meta:
        verbose_name_plural = 'подписки'
        constraints = [
            models.UniqueConstraint(
                name='unique_relationships_follow_ups',
                fields=["user", "author"],),
            models.CheckConstraint(
                name='prevent_self_follow',
                check=~models.Q(user=models.F("author")),),
        ]

    def __str__(self):
        return (f'Пользователь {self.user.username}'
                f'подписан на {self.author.username}')

yatube/posts/forms.py
from django import forms

from .models import Post, Comment, Group


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Введите текст',
                  'group': 'Выберите группу',
                  'image': 'Добавьте файл'}
        help_texts = {'text': 'Любую абракадабру',
                      'group': 'Из уже существующих',
                      'image': 'Фоточку например'}


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Введите текст', }
        help_texts = {'text': 'Любую абракадабру', }


class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ('title', 'slug', 'description')
        labels = {'title': 'Hазвание группы',
                  'slug': 'Cсылка группы',
                  'description': 'Oписание группы'}
        help_texts = {'title': 'Введите название группы',
                      'slug': 'Введите ссылкy группы',
                      'description': 'Введите описание группы'}

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from .forms import PostForm, CommentForm, GroupForm
from .models import Group, Post, User, Follow, Comment
from .utils import paging


def index(request):
    posts = Post.objects.select_related('author', 'group').all()
    page_obj = paging(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_index(request):
    groups = Group.objects.all()
    page_obj = paging(request, groups)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_index.html', context)


def group_posts(request, group_list):
    group = get_object_or_404(Group, slug=group_list)
    posts = group.posts.select_related('author').all()
    page_obj = paging(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


@login_required
def group_create(request):
    form = GroupForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/group_create.html', {'form': form})
    new_group = form.save(commit=False)
    new_group.author = request.user
    new_group.save()
    return redirect('posts:group_index')


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group').all()
    page_obj = paging(request, posts)
    following = request.user.is_authenticated and author.following.filter(
        user=request.user).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('author').prefetch_related(
            'comments__author'),
        id=post_id)
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'comments': post.comments.all(),
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        return render(request, 'posts/post_create.html', {'form': form})
    new_post = form.save(commit=False)
    new_post.author = request.user
    new_post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if not form.is_valid():
        return render(request, 'posts/post_create.html', {'form': form})
    form.save()
    return redirect('posts:post_detail', post_id)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user == post.author:
        post.delete()
    return redirect('posts:profile', request.user.username)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user == comment.author:
        comment.delete()
    return redirect('posts:post_detail', comment.post.pk)


@login_required
def follow_index(request):
    posts = Post.objects.select_related('author').filter(
        author__following__user=request.user)
    page_obj = paging(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=request.user,
            author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow,
        user=request.user,
        author__username=username).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-secondary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div>
    <div class>
      <h5 class="mt-0">
        <a class="blog-post-meta link-dark" href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        {{ comment.text|linebreaks }}
    </div>
    {% if user == comment.author %}
      <a class="blog-post-meta link-dark" href="{% url 'posts:post_detail' post.id %}">
        удалить
      </a>
    {% endif %}
  </div>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
  <ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link text-dark" href="?page=1">Первая</a></li>
    <li class="page-item">
      <a class="page-link text-dark" href="?page={{ page_obj.previous_page_number }}">
        Предыдущая
      </a>
    </li>
  {% endif %}
  {% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
      <li class="page-item disabled text-secondary">
        <span class="page-link">{{ i }}</span>
      </li>
    {% else %}
      <li class="page-item">
        <a class="page-link text-dark" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link text-dark" href="?page={{ page_obj.next_page_number }}">
        Следующая
      </a>
    </li>
    <li class="page-item">
      <a class="page-link text-dark" href="?page={{ page_obj.paginator.num_pages }}">
        Последняя
      </a>
    </li>
  {% endif %}
  </ul>
  </nav>
{% endif %}

yatube/templates/posts/includes/post.html
{% load thumbnail %}
<div class="card">
  <h5 class="card-header">
    <div>
      {% if not group_list %}
        {% if post.group %} 
          <a href="{% url 'posts:group_list' post.group.slug %}" class="blog-post-meta link-dark">
            {{ post.group.title }} 
          </a> |
        {% endif %}
      {% endif %}
      <a {% if not profile %}href="{% url 'posts:profile' post.author.username %}{% endif %}" class="blog-post-meta link-dark">
        {{ post.author.get_full_name }}
      </a>
    </div>
    {% if user == post.author %}
      {% if profile or post_detail %}
        <div class="drop">
          <button class="nav-btn">&#8943;</button>
          <div class="nav-list nav-tabs">
            <h6><a class="nav-link" href="{% url 'posts:post_edit' post.id %}" style="color:black">Редактировать</a></h6>
            <h6><a class="nav-link" href="{% url 'posts:post_delete' post.id %}" style="color:black">Удалить</a></h6>
          </div>
        </div>
      {% endif %}
    {% endif %}
    </h5>
  <div class="card-body">
    <h6 class="card-subtitle">
      {{ post.pub_date|date:"j M Y G:i" }}
    </h6>
    {% thumbnail post.image "960x400" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {{ post.text|linebreaks }}
    {% if not post_detail %}
      <a type="button" href="{% url 'posts:post_detail' post.id %}" class="btn btn-secondary btn-sm">Открыть</a>
    {% endif %}
  </div>
</div>

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link link-dark {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Главная
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link link-dark {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Подписки
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link link-dark {% if groups %}active{% endif %}"
           href="{% url 'posts:group_index' %}"
        >
          Группы
        </a>
      </li>
    </ul>
  </div>
{% endif %}