yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:group_list>/', views.group_posts, name='group_list'),
    path('groups/', views.group_index, name='group_index'),
    path('groups/create/', views.group_create, name='group_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/comment/delete/',
        views.delete_comment,
        name='delete_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordChangeView as PChangeV,
                                       PasswordChangeDoneView as PChDoneV,
                                       PasswordResetDoneView as PReDoneV,
                                       PasswordResetView as PReV,
                                       PasswordResetCompleteView as PReCompV,
                                       PasswordResetConfirmView as PReConfV)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PChangeV.as_view(template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PChDoneV.as_view(template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PReV.as_view(template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PReDoneV.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PReConfV.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PReCompV.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'

handler500 = 'core.views.server_error'

handler403 = 'core.views.permission_denied'

handler400 = 'core.views.bad_request'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models

from core.models import CreatedModel, User


class Post(CreatedModel):
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta(CreatedModel.Meta):
        verbose_name_plural = 'посты'
        default_related_name = 'posts'


class Group(models.Model):
    title = models.CharField(
        'название_группы',
        max_length=200,
        help_text='Введите название группы',
    )
    slug = models.SlugField(
        'ссылка',
        blank=True,
        null=False,
        unique=True,
        help_text='Введите ссылкy группы',
    )
    description = models.TextField(
        'описание группы',
        help_text='Введите описание группы'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='автор',
    )

    class Meta:
        verbose_name_plural = 'группы'

    def __str__(self):
        return self.title


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='пост'
    )

    class Meta(CreatedModel.Meta):
        verbose_name_plural = 'коментарии'
        default_related_name = 'comments'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='который подписывается',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='на которого подписываются',
    )

    class Meta:
        verbose_name_plural = 'подписки'
        constraints = [
            models.UniqueConstraint(
                name='unique_relationships_follow_ups',
                fields=["user", "author"],),
            models.CheckConstraint(
                name='prevent_self_follow',
                check=~models.Q(user=models.F("author")),),
        ]

    def __str__(self):
        return (f'Пользователь {self.user.username}'
                f'подписан на {self.author.username}')

yatube/posts/forms.py
from django import forms

from .models import Post, Comment, Group


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Введите текст',
                  'group': 'Выберите группу',
                  'image': 'Добавьте файл'}
        help_texts = {'text': 'Любую абракадабру',
                      'group': 'Из уже существующих',
                      'image': 'Фоточку например'}


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Введите текст', }
        help_texts = {'text': 'Любую абракадабру', }


class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ('title', 'slug', 'description')
        labels = {'title': 'Hазвание группы',
                  'slug': 'Cсылка группы',
                  'description': 'Oписание группы'}
        help_texts = {'title': 'Введите название группы',
                      'slug': 'Введите ссылкy группы',
                      'description': 'Введите описание группы'}

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from .forms import PostForm, CommentForm, GroupForm
from .models import Group, Post, User, Follow, Comment
from .utils import paging


def index(request):
    posts = Post.objects.select_related('author', 'group').all()
    page_obj = paging(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_index(request):
    groups = Group.objects.all()
    page_obj = paging(request, groups)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_index.html', context)


def group_posts(request, group_list):
    group = get_object_or_404(Group, slug=group_list)
    posts = group.posts.select_related('author').all()
    page_obj = paging(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


@login_required
def group_create(request):
    form = GroupForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/group_create.html', {'form': form})
    new_group = form.save(commit=False)
    new_group.author = request.user
    new_group.save()
    return redirect('posts:group_index')


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group').all()
    page_obj = paging(request, posts)
    following = request.user.is_authenticated and author.following.filter(
        user=request.user).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('author').prefetch_related(
            'comments__author'),
        id=post_id)
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'comments': post.comments.all(),
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        return render(request, 'posts/post_create.html', {'form': form})
    new_post = form.save(commit=False)
    new_post.author = request.user
    new_post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if not form.is_valid():
        return render(request, 'posts/post_create.html', {'form': form})
    form.save()
    return redirect('posts:post_detail', post_id)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user == post.author:
        post.delete()
    return redirect('posts:profile', request.user.username)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user == comment.author:
        comment.delete()
    return redirect('posts:post_detail', comment.post.pk)


@login_required
def follow_index(request):
    posts = Post.objects.select_related('author').filter(
        author__following__user=request.user)
    page_obj = paging(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=request.user,
            author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow,
        user=request.user,
        author__username=username).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Подписки
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6 p-5">
      <h1> Последние обновления </h1>
      <br>
      {% include 'posts/includes/switcher.html' with follow=True %}
      <br>
      {% for post in page_obj %}
        {% include 'posts/includes/post.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </div>
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_create.html
{% extends 'base.html' %}
{% block title %}
  Новая группа
{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-6 p-5">
        <div class="card">
          {% include 'includes/errors_form.html' %}
          <div class="card-header"> 
            Новая группа
          </div>
          <div class="card-body">        
            <form method="post" action="{{ request.path }}">            
                {% csrf_token %}
                {% include 'includes/cycle_form.html' %}
                <button type="submit" class="btn btn-secondary">
                  Создать
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_index.html
{% extends 'base.html' %}
{% block title %}
  Группы
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6 p-5">
      <h1> Группы </h1>
      <br>
      {% include 'posts/includes/switcher.html' with groups=True %}
      <br>
      <a type="button" href="{% url 'posts:group_create' %}" class="btn btn-secondary">Создать группу</a>
      <br><br>
      {% for group in page_obj %}
        <div class="card">
          <h5 class="card-header">
            <div> 
              <a href="{% url 'posts:group_list' group.slug %}" class="blog-post-meta link-dark">
                {{ group.title }} 
              </a>
            </div>
          </h5>
          <div class="card-body">
            {{ group.description|linebreaks }}
          </div>
        </div>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </div>
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html'%} 
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %} 
{% block content %}
  <div class="container">
    <div class="row">
      <aside class="col-12 col-md-3">
        <div class="card" style="">
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><h5>{{ group.title }}</h5></li>
            <li class="list-group-item"><h6>{{ group.description }}</h6></li>
          </ul>
        </div>
      </aside>
      <article class="col-12 col-md-7">
        {% for post in page_obj %}
          {% include 'posts/includes/post.html' with group_list=True %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </article>
    </div>
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock%}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Главная
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6 p-5">
      <h1> Последние обновления </h1>
      <br>
      {% include 'posts/includes/switcher.html' with index=True %}
      <br>
      {% load cache %}
      {% cache 30 sidebar index page_obj.number %}
        {% for post in page_obj %}
          {% include 'posts/includes/post.html' %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      {% endcache %}
    </div>
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
  {% if form.instance.pk %}Редактирование поста{% else %}Новый пост{% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-6 p-5">
        <div class="card">
          {% include 'includes/errors_form.html' %}
          <div class="card-header"> 
            {% if form.instance.pk %}Редактирование поста{% else %}Новый пост{% endif %}
          </div>
          <div class="card-body">        
            <form method="post" action="{{ request.path }}" enctype="multipart/form-data">            
                {% csrf_token %}
                {% include 'includes/cycle_form.html' %}
                <button type="submit" class="btn btn-secondary">
                  {% if form.instance.pk %}Сохранить{% else %}Добавить{% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Детали поста 
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
      <div class="col-md-6 p-5">
        {% include 'posts/includes/post.html' with post_detail=True %}
        {% include 'posts/includes/comments.html' %}
      </div>
  </div>
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Все посты автора
{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <aside class="col-12 col-md-3">
        <div class="card" style="">
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><h5>{{ author.get_full_name }}</h5></li>
            <li class="list-group-item"><h6>постов {{ author.posts.all.count }}</h6></li>
            <li class="list-group-item">
              <h6>подписок {{ user.follower.count }}</h6>
              <h6>подписчиков {{ user.following.count }}</h6>
            </li>
          </ul>
        </div>
        <br>
        {% if user.is_authenticated%}
          {% if not user == author %}
            {% if following %}
              <a
                class="btn btn-lg btn-secondary"
                href="{% url 'posts:profile_unfollow' author.username %}" role="button"
              >
                Отписаться
              </a>
            {% else %}
              <a
                class="btn btn-lg btn-secondary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
              >
                Подписаться
              </a>
            {% endif %}
          {% else %}
            <a class="btn btn-secondary" 
            href="{% url 'users:password_change' %}" role="button">Изменить пароль</a>
          {% endif %}
        {% endif %}
      </aside>
      <article class="col-12 col-md-7">
        {% for post in page_obj %}
          {% include 'posts/includes/post.html' with profile=True %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </article>
    </div>
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 
  